// "use client";

import Link from 'next/link'
import './globals.css'
import { Control } from './Control';


export const metadata = {
  title: 'Web turtolials',
  description: 'Generated by JUN HEE',
}

export default async function RootLayout({ children }) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache: 'no-store'});
  const topics = await res.json();
  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.map((topics)=>{
            return <li key={topics.id}><Link href={`/read/${topics.id}`}>{topics.title}</Link></li>
          })}
        </ol>
          {children}
          <Control/>
      </body>
    </html>
  )
}
